---
title: "SimTOST"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SimTOST}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
bibliography: '`r system.file("references.bib", package="SimTOST")`'
editor_options: 
  markdown: 
    wrap: sentence
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `SimTOST` is an R package to facilitate sample size estimation for clinical trials.
It uses a simulation-based approach to empirically determine the sample size for multi-arm trials with one or more endpoints.
The vignettes below illustrate the use of the R package using published data from a randomized, phase I pharmacokinetic study comparing SB2 versus Remicade in healthy subjects [@shin_randomized_2015].

## Example Data

In this section, we will briefly explain a trial, [NCT01922336](https://clinicaltrials.gov/study/NCT01922336#study-overview), as an illustrative example, in which its sample size can be calculated using `SimTOST` package.
This Phase 1 clinical study, designed as a single-blind, parallel-group, single-dose trial, evaluates the pharmacokinetics, safety, and immunogenicity of a biosimilar drug (SB2) w.r.t. two infliximab reference products: EU-sourced Remicade (EU-INF) and US-sourced Remicade (US-INF).
Subjects receive a 5 mg/kg dose via intravenous infusion, with premedication administered to prevent infusion-related reactions.
The study spans 10 weeks.
Safety assessments include vital signs, laboratory tests, and adverse event recording, while immunogenicity is evaluated through blood samples for anti-drug antibodies.
Pharmacokinetic analysis involves multiple endpoints, i.e., Cmax, Tmax, AUCInf, and AUClast.
The following table, describe the PICO element of this study.

+---------------------+-------------------------------------------------------------------------------------------------------------+
| PICO's element      | Details                                                                                                     |
+=====================+=============================================================================================================+
| Patient/ population | -   Healthy female subjects of non-childbearing potential and healthy male subjects                         |
|                     |                                                                                                             |
|                     | -   Age: 18 to 55 years (Adults)                                                                            |
|                     |                                                                                                             |
|                     | -   Body weight: 60.0 to 94.9 kg                                                                            |
|                     |                                                                                                             |
|                     | -   BMI: 20.0 to 29.9 kg/m²                                                                                 |
+---------------------+-------------------------------------------------------------------------------------------------------------+
| Intervention        | -   SB2, single dose of 5 mg/kg                                                                             |
+---------------------+-------------------------------------------------------------------------------------------------------------+
| Comparison          | -   EU-sourced Remicade, intravenous infusion for 120 min on the first day of study                         |
|                     | -   US-sourced Remicade, intravenous infusion for 120 min on the first day of study                         |
+---------------------+-------------------------------------------------------------------------------------------------------------+
| Outcomes            | Primary:                                                                                                    |
|                     |                                                                                                             |
|                     | -   Area Under the Concentration-time Curve From Time Zero to Infinity (AUCinf)                             |
|                     |                                                                                                             |
|                     | -   Maximum Serum Concentration (Cmax)                                                                      |
|                     |                                                                                                             |
|                     | -   Area Under the Concentration-time Curve From Time Zero to the Last Quantifiable Concentration (AUClast) |
|                     |                                                                                                             |
|                     | Secondary:                                                                                                  |
|                     |                                                                                                             |
|                     | -   Time to Cmax (Tmax)                                                                                     |
+---------------------+-------------------------------------------------------------------------------------------------------------+

: PICO table of the trial

## Vignettes

Each vignette will focus on a specific scenario as explained as follows:

+-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Vignette                                            | Details                                                                                                                                                                                                                                                                                                                                  |
+=====================================================+==========================================================================================================================================================================================================================================================================================================================================+
| [2 arms, 1 endpoint](individual_ep.html)            | In this vignette, we will explore 4 examples of sample size calculation for 2 arms and 1 endpoint trial with the following assumptions:                                                                                                                                                                                                  |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
| |                                                   | | 1. Common Standard Deviation (SD), Ratio of Means (ROM) as parameter tested, parallel design, and lognormal distribution assumption.                                                                                                                                                                                                   |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | | 2. The same assumptions with (1), but using different SD assumption for each arm.                                                                                                                                                                                                                                                      |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | | 3. The same assumptions with (1), but the parameter tested is Difference of Means (DOM) and assume Normal distribution.                                                                                                                                                                                                                |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | | 4. The same assumptions with (1), but the study design is cross-over.                                                                                                                                                                                                                                                                  |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | | For each example, we will compare the result with [PowerTOST](https://cran.r-project.org/web/packages/PowerTOST/PowerTOST.pdf) result.                                                                                                                                                                                                 |
+-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [3 arms, 1 endpoint](individual_ep_three_arms.html) | This vignette focuses on sample size calculation examples of 3 arms and 1 endpoint, parallel design trial. The parameter tested is ROM with common SD assumption.                                                                                                                                                                        |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
| |                                                   | In this vignette, we will use this trial as the use case. In the first example, we only care about the comparison of SB2 vs EU Remicade and SB2 vs US Remicade. In the second example, we set the situation as in Example 1, however we define a different lower and upper equivalence.                                                  |
+-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [2 arms, 3 endpoints](three_ep_two_arms.html)       | In this vignette, we will show the example of using `SimTOST` package for 2 arms and 3 endpoints trial. We will also use this trial as illustrative example. There are 5 situations considered, as follows:                                                                                                                        |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 1.  Common SD assumption for each biosimilar, Ratio of Means (ROM) as parameter tested, parallel design, and lognormal distribution assumption, no multiplicity adjustment, and assume that equivalence is only needed for one of the endpoints.                                                                                         |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 2.  The same assumptions with (1). However, in this example, we assume that there is a correlation between endpoint.                                                                                                                                                                                                                     |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 3.  The same assumptions with (1), except that we assume the equivalence for all endpoints. Also, we use Bonferroni adjustment.                                                                                                                                                                                                          |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 4.  The same assumptions with (3), but we change the adjustment into k-adjustment.                                                                                                                                                                                                                                                       |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 5.  The same assumptions with (3), but we change the adjustment into sequential adjustment.                                                                                                                                                                                                                                              |
+-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [3 arms, 3 endpoints](three_ep_three_arms.html)     | In this vignette, we will show the examples of sample size calculation for 3 arms and 3 endpoints trial. Again, we use this trial as an illustration. The situations considered are as follows:                                                                                                                                          |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 1.  Common SD assumption for each biosimilar, Ratio of Means (ROM) as parameter tested, parallel design, and lognormal distribution assumption, no multiplicity adjustment, and assume only need equivalence for one of the endpoints. Also, we compare the biosimilars simultaneously, i.e., SB2 vs EU Remicade and SB2 vs US Remicade. |
|                                                     |                                                                                                                                                                                                                                                                                                                                          |
|                                                     | 2.  The same assumptions with (1). However, we need equivalence for all endpoints. Besides, we use sequential adjustment.                                                                                                                                                                                                                |
+-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Vignette overview

# References
